spring:
  application:
    name: binance-futures-level-breakout-bot
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: 443
  shutdown: graceful
  ssl:
    enabled: true
    key-store: "file:${TLS_KEYSTORE_PATH}"
    key-store-password: "${TLS_KEYSTORE_PASSWORD}"
    key-store-type: PKCS12

bot:
  binance:
    startup-enabled: true
  security:
    username: "${BOT_BASIC_USERNAME}"
    password: "${BOT_BASIC_PASSWORD}"
